---
title: "Cangrelor Regression Analysis"
author: "Brian Gulbis, PharmD, BCPS"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
library(broom)

df <- read_excel(
    "../data/external/cangrelor_pci_data.xlsx",
    skip = 1,
    # range = "A2:C78",
    col_names = c(
        "fin",
        "cangrelor",
        "male",
        "race_white",
        "race_black",
        "race_asian",
        "race_hispanic",
        "race_other",
        "age",
        "height",
        "weight",
        "bmi",
        "pmh_stroke",
        "pmh_chf",
        "pmh_dm",
        "pmh_hepatic",
        "pmh_acs",
        "pmh_renal",
        "pressors",
        "mcs_device",
        "pci_indication",
        "pci_duration",
        "femoral",
        "fondaparinux",
        "lmwh",
        "heparin",
        "aspirin",
        "bivalirudin",
        "dti",
        "gp2b3ai",
        "tpa",
        "clopidogrel",
        "prasugrel",
        "ticagrelor",
        "composite",
        "mortality",
        "stent_thromb",
        "stroke",
        "mi",
        "revasc",
        "bleed",
        "timi_min",
        "timi_medattent",
        "timi_minor",
        "timi_major",
        "timi_min_maj",
        "barc1",
        "barc2",
        "barc3",
        "barc5",
        "barc3_5",
        "transfusions"
    ),
    col_types = c(
        "text",
        rep("logical", 7),
        rep("numeric", 4),
        rep("logical", 7),
        rep("text", 2),
        "numeric",
        rep("logical", 29),
        "numeric"
    )
) %>%
    mutate(
        race = case_when(
            race_white ~ "white",
            race_black ~ "african_american",
            race_asian ~ "asian",
            race_hispanic ~ "hispanic",
            race_other ~ "other"
        ),
        antiplt_agent = case_when(
            clopidogrel ~ "clopidogrel",
            prasugrel ~ "prasugrel",
            ticagrelor ~ "ticagrelor",
            TRUE ~ NA_character_
        )
    ) %>%
    mutate_at(c("gp2b3ai", "lmwh", "aspirin", "tpa"), list(~coalesce(., FALSE))) %>%
    mutate_at("mcs_device", na_if, y = 0) %>%
    mutate(
        mcs = !is.na(mcs_device),
        oral_antiplt = !is.na(antiplt_agent)
    ) %>%
    mutate_at(c("mcs_device", "antiplt_agent"), list(~coalesce(., "none"))) %>%
    mutate_at(c("mcs_device", "pci_indication"), str_to_upper) %>%
    mutate_at(c("antiplt_agent", "race"), str_to_title) %>%
    mutate_at(c("mcs_device", "pci_indication", "antiplt_agent", "race"), fct_infreq) %>%
    mutate_at("antiplt_agent", list(~fct_relevel(., "None", after = 0)))

df_bmi <- filter(df, !is.na(bmi))

```

```{r}
summary(df)
```

```{r}
library(MASS)
```

# Composite Outcome

## Univariate Regression Models

```{r}
glm(
    composite ~ cangrelor, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

```{r}
glm(
    composite ~ mcs, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

## Multivariate Regression Models

```{r}
glm(
    composite ~ cangrelor + mcs + pressors, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

## Stepwise Regression Models

```{r}
glm(
    composite ~ cangrelor + male + race + age + bmi + pmh_stroke + pmh_chf + pmh_dm + pmh_hepatic + pmh_acs + pmh_renal + pressors + mcs + pci_indication + pci_duration + femoral + gp2b3ai + antiplt_agent + transfusions, 
    family = "binomial", 
    data = df
) %>%
    stepAIC(direction = "backward", trace = FALSE) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

```{r}
glm(
    composite ~ cangrelor + male + race + age + bmi + pmh_stroke + pmh_chf + pmh_dm + pmh_hepatic + pmh_acs + pmh_renal + pressors + pci_indication + pci_duration + femoral + gp2b3ai + antiplt_agent + transfusions, 
    family = "binomial", 
    data = df
) %>%
    stepAIC(direction = "backward", trace = FALSE) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

# Bleeding

## Univariate Regression Models

```{r}
glm(
    bleed ~ cangrelor, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

```{r}
glm(
    bleed ~ gp2b3ai, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

```{r}
glm(
    bleed ~ oral_antiplt, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

```{r}
glm(
    bleed ~ antiplt_agent, 
    family = "binomial", 
    data = df
) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```

## Multivariate Regression Models


## Stepwise Regression Models

```{r}
glm(
    bleed ~ cangrelor + male + race + age + bmi + pmh_stroke + pmh_chf + pmh_dm + pmh_hepatic + pmh_acs + pmh_renal + pressors + mcs + pci_indication + femoral + antiplt_agent + gp2b3ai + transfusions, 
    family = "binomial", 
    data = df
) %>%
    stepAIC(direction = "backward", trace = FALSE) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```


```{r}
df_nomcs <- filter(df, !mcs)

glm(
    composite ~ cangrelor + male + race + age + bmi + pmh_stroke + pmh_chf + pmh_dm + pmh_hepatic + pmh_acs + pmh_renal + pressors + pci_indication + pci_duration + femoral + gp2b3ai + antiplt_agent + transfusions, 
    family = "binomial", 
    data = df_nomcs
) %>%
    stepAIC(direction = "backward", trace = FALSE) %>%
    tidy(conf.int = TRUE, exponentiate = TRUE) %>%
    knitr::kable(digits = 3)
```
