WITH CANGRELOR_PTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCOUNTER.DISCH_DT_TM,
		'CANGRELOR' AS PT_GROUP
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	TRUNC(pi_from_gmt(PROCEDURE.PROC_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS PROCEDURE_DATE,
	NOMENCLATURE.SOURCE_IDENTIFIER,
	NOMENCLATURE.SOURCE_STRING,
	pi_get_cv_display(NOMENCLATURE.SOURCE_VOCABULARY_CD) AS SOURCE_VOCABULARY
FROM 
	CANGRELOR_PTS,
	ENCNTR_ALIAS,
	NOMENCLATURE,
	PROCEDURE
WHERE
	CANGRELOR_PTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND CANGRELOR_PTS.ENCNTR_ID = PROCEDURE.ENCNTR_ID
	AND PROCEDURE.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
	AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
	AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^027[0-3]') > 0 
