WITH ICD AS (
	SELECT DISTINCT
		NOMENCLATURE.NOMENCLATURE_ID
	FROM
		NOMENCLATURE
	WHERE
		REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^027[0-3]') > 0 
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 761 -- Procedure
), PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID
	FROM
		ENCOUNTER,
		ICD,
		PROCEDURE
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.REG_DT_TM BETWEEN 
			pi_to_gmt(DATE '2016-01-01', pi_time_zone(1, @Variable('BOUSER'))) 
			AND pi_to_gmt(DATE '2019-07-01', pi_time_zone(1, @Variable('BOUSER'))) 
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD = 42631 -- Inpatient
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND ENCOUNTER.ENCNTR_ID = PROCEDURE.ENCNTR_ID
		AND ICD.NOMENCLATURE_ID = PROCEDURE.NOMENCLATURE_ID
), CANGRELOR_PTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		'CANGRELOR' AS PT_GROUP
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), ALL_PTS AS (
	SELECT ENCNTR_ID
	FROM CANGRELOR_PTS
	
	UNION
	
	SELECT ENCNTR_ID
	FROM PATIENTS	
)

SELECT
	ALL_PTS.ENCNTR_ID,
	ENCOUNTER.PERSON_ID,
	ENCOUNTER.ENCNTR_TYPE_CLASS_CD,
	pi_get_cv_display(ENCOUNTER.ENCNTR_TYPE_CLASS_CD) AS ENCNTR_TYPE_CLASS,
	ENCOUNTER.REG_DT_TM,
	ENCOUNTER.DISCH_DT_TM,
	CANGRELOR_PTS.PT_GROUP
FROM 
	ALL_PTS,
	CANGRELOR_PTS,
	ENCOUNTER
WHERE
	ALL_PTS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND ALL_PTS.ENCNTR_ID = CANGRELOR_PTS.ENCNTR_ID(+)